---
tower_hostname: ""
tower_oauthtoken: ""
tower_validate_certs: false
tower_configuration_group_secure_logging: "{{tower_configuration_secure_logging | default(false)}}"
tower_groups:
  - name: localhost
    inventory: localhost
    variables:
      some_var: some_val
      ansible_connection: local
